### ISSUE TITLE
商品一覧画面（admin-index.blade.php）の修正

### ISSUE THREAD

**Issue by and1-sho** [and1-sho/sheep-bookstore_app#28]
### 要望箇所
商品一覧画面(admin-index.blade.php)のモーダルの×印

### 要望内容
×印のクリック範囲が狭い為、クリックしづらいと感じました

### 提案
もう少しアバウトな範囲をクリックしてもモーダルが閉じるようしてほしい

**Comment by ringo-117** [comment]
×印のクリック範囲を修正しました。
ご確認よろしくお願いします。
