### ISSUE TITLE
商品一覧画面(admin-index.blade.php)の新規登録ボタンの修正

### ISSUE THREAD

**Issue by and1-sho** [and1-sho/sheep-bookstore_app#33]
## 要望箇所
商品一覧画面(admin-index.blade.php)の新規登録ボタン

## 要望内容
新規登録ボタンのクリック範囲が狭い為、クリックしづらいと感じました

## 提案
ボタンの範囲ぐらいをクリック範囲にして欲しいです

**Comment by ringo-117** [comment]
修正が完了しました。
よろしくお願いします。
